accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.indexView, name="home"),
    path('dashboard/', views.dashboardView, name="dashboard"),
    path('login/', LoginView.as_view(), name="login_url"),
    path('register/', views.registerView, name="register_url"),
    path('logout/', LogoutView.as_view(next_page="dashboard"), name="logout"),
]

myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/', views.delete, name='delete'),
    path('profile/', views.profile, name='profile'),
    path('library/', views.library, name='library'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
	status = models.CharField(max_length=300)
	created_at = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

myapp/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    status = forms.CharField(widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'How is your day?'}))

    class Meta:
        model = Status
        fields = ['status']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def indexView(request):
    return render(request, 'index.html')

@login_required
def dashboardView(request):
    return render(request, 'dashboard.html')

def registerView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_url')
    else:
        form = UserCreationForm()
    
    return render(request, 'registration/register.html', {'form':form})

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import Context, loader
from .forms import StatusForm
from .models import Status
from django.contrib.auth import authenticate, login as auth_SignIn, logout as auth_SignOut

def home(request):
	form = StatusForm(request.POST or None)
	response = {}
	if(request.method == "POST" and form.is_valid()):
		if (form.is_valid()):
			status = request.POST.get("status")
			created_at = request.POST.get("created_at")
			Status.objects.create(status=status, created_at=created_at)
			return redirect('/')
	else:
		allStatus = Status.objects.all().order_by('-id')
		response['form'] = form
		response['allStatus'] = allStatus
		return render(request, 'status.html', response)

def delete(request):
	allStatus = Status.objects.all().delete()
	return redirect('/')

def profile(request):
	return render(request, 'profile.html')

def library(request):
	return render(request, 'library.html')

accounts/templates/dashboard.html
{% extends 'index.html' %}

{% block content %}
    <h1>{{user.username}}'s dashboard.</h1>
    <div id="nav">
        <a href="{% url 'home' %}" class="mr-3" style="text-decoration:none; color:#b6617d;">go to homepage</a>
    </div>
{% endblock %}

accounts/templates/index.html
<!DOCTYPE html>
<html>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=DM+Serif+Display|Gilda+Display|Playfair+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href={% static 'style3.css' %}>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    <head>
        <title>Accounts Page</title>
    </head>
    <body>
        {% block content %}
            <h1>&#9829;	welcome home &#9829;</h1>
            <div class="container">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}" class="mr-3" style="text-decoration:none; color:#b6617d;">Logout</a>
                        {% else %}
                            <h2>have you registered your account?</h2>
                            <a href="{% url 'login_url' %}" class="mr-3" style="text-decoration:none; color:#b6617d; text-align: center;">Login</a>
                            <a href="{% url 'register_url' %}" class="mr-3" style="text-decoration:none; color:#b6617d; text-align: center;">Register</a>
                        {% endif %}   
                    </div>
                </div>
            </div>   
        {% endblock %}
    </body>
</html>

myapp/templates/library.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=DM+Serif+Display|Gilda+Display|Playfair+Display|Quicksand&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <div class="nav">
        <a href="{% url 'myapp:home' %}" class="mr-3" style="text-decoration:none; color:#b6617d;">Write your feelings here</a>
        <a href="{% url 'myapp:profile' %}" style="text-decoration:none; color:#b6617d;">Get to Know Me</a>
    </div>

<div class='library'>
    <div class = "newsletter">
        <h1>what would you like to read today?</h1>

        <div class="search-box d-flex">
            <input class="form-control" type="search" id="field" name="" value="" placeholder="Type to search">
            <button class="search-btn" type="button" name="button"><i class="fas fa-search" aria-hidden="true"></i></button>
        </div>
      
        <div class="table-responsive mt-4">
            <table class="table table-light table-striped" id="books"></table>
        </div>
    </div> 
    
</div>
<script src="https://code.jquery.com/jquery-1.11.3.js"></script>
<script src="{% static 'script2.js' static %}"></script>

</body>
</html>

myapp/templates/profile.html
<!DOCTYPE html>
<html>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=DM+Serif+Display|Gilda+Display|Playfair+Display&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-2.1.3.js"></script>
	<script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

<head>
    <title>Profile Page</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                <img src="{% static 'Kamila.jpg' %}" style="height: auto; width: 100%;">                
            </div>
            <div class="col-8">
                <div class="switcher-buttons">
                    <h5 id="click-info">click for a surprise</h5>
                    <div class="toggle-container">
                        <input type="checkbox" id="switch" name="theme"/><label for="switch">Toggle</label>
                    </div>
                </div>
                <div class="profile">
                    <div class="description">
                        <h1 id="name">kamila alifia.</h1>
                        <br></br>
                        <p>Hi, nice to meet you! My name is Kamila. I have an interest in programming and technology.</p>
                        <p>I am a Computer Science student at University of Indonesia, class of 2018.</p>
                        <p>Hopefully, I can build my own startup after I graduate from here.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>   
    <div id="accordion">
        <h4>Activities</h4>
        <div>
            <p>Currently struggling to pass this semester. Please pray for me whoever read this.</p>
        </div>
        <h4>Experiences</h4>
        <div>
            <ul>
                <li>Staff of Liaison Officer - Open House Fasilkom UI 2019</li>
                <li>Staff of Fundraising - Compfest 11</li>
                <li>Vice Person in Charge of Sponsorship - CGT in Action</li>
                <li>Staff of Public Relation - Educare 2019</li>
                <li>Staff of Public Relation - Open House Fasilkom UI 2018</li>
                <li>Staff of Public Relation - Universiade 2018</li>
            </ul>
        </div>
        <h4>Achievements</h4>
        <div>
            <p>I don't want to brag, sorry :)</p>
        </div>
    </div>
    
    <div class="nav">
        <a href="{% url 'myapp:home' %}" class="mr-3" style="text-decoration:none; color:#b6617d;">Write your feelings here</a>
        <a href="{% url 'myapp:library' %}" style="text-decoration:none; color:#b6617d;">Search for a book</a>    
    </div>
    
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

myapp/templates/status.html
<!DOCTYPE html>
<html>
	{% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=DM+Serif+Display|Gilda+Display|Playfair+Display&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<head>
	<title>Statuses Page</title>
</head>

<body>
	<div class="nav">
		<a href="{% url 'myapp:profile' %}" class="mr-3" style="text-decoration:none; color:#b6617d;">Get to Know Me</a>
		<a href="{% url 'myapp:library' %}" style="text-decoration:none; color:#b6617d;">Search for a Book</a>
	</div>
	
	<h1 class="mt-3">Halo, apa kabar?</h1>
	<form method="POST", action="{% url 'myapp:home' %}">
		{% csrf_token %}
		<div class="statusform mt-3">
			<h2>How are you?</h2>
			<div class="mt-3">
				<div class="fields text-center statusbar container pt-3" style="margin: auto;">
					{% for field in form %}
						<p>{{ field }}</p>
						{% endfor %}
				</div>
				<div class="d-flex justify-content-center mt-4">
					<button type="submit" class="submit" id="submit">Submit</button>
				</div>
			</div>
		</div>
	</form>
	
	<div class="statusposts container statusbar mt-4 mb-5">
		<h2 class="mt-3">Status</h2>
		{% if allStatus %}
		<div class="posted">
			{% for statuses in allStatus %}
				<hr>
				<div class="mt-3">
					<h3>{{ statuses.status }}</h3>
					{{ statuses.created_at }}
				</div>
			{% endfor %}
			<hr>
			<form method="POST" action="{% url 'myapp:delete' %}"> {% csrf_token %}
				<button type="submit" class="submit mb-4">Clear Statuses</button>
			</form>
		</div>
		{% else %}
			<h5>Your statuses will be shown here!</h5>
		{% endif %}
	</div>
</body>
</html>